const BUTTON_CLICK = 'app/user/SET_BUTTON_CLICK';
const SET_VALUE = 'app/user/SET_VALUE';
const AUTHENTICATE_USER = 'app/user/AUTHENTICATE_USER';
const SET_WALLET_ADDRESS = 'app/user/SET_WALLET_ADDRESS';

export {
  BUTTON_CLICK,
  SET_VALUE,
  AUTHENTICATE_USER,
  SET_WALLET_ADDRESS,
};
